In [23]:
# Домашнє завдання 1
import numpy as np
comment = '''\n1 Створіть одновимірний масив (вектор)
		з першими 10-ма натуральними числами
		та виведіть його значення.'''
print(comment)
m1 = np.arange(1, 11)
print('\nRESULT:')
print(m1)
m1_1 = np.linspace(1, 10, num=10)
print('\nRESULT:')
print(m1_1)


1 Створіть одновимірний масив (вектор)
		з першими 10-ма натуральними числами
		та виведіть його значення.

RESULT:
[ 1  2  3  4  5  6  7  8  9 10]

RESULT:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [24]:
comment = '''\n2 Створіть двовимірний масив (матрицю) розміром 3x3,
		заповніть його нулями
		та виведіть його значення.'''
print(comment)
m1 = np.zeros((3,3), dtype=int)
print('\nRESULT:')
print(m1)


2 Створіть двовимірний масив (матрицю) розміром 3x3,
		заповніть його нулями
		та виведіть його значення.

RESULT:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
comment = '''\n3 Створіть масив розміром 5x5,
		заповніть його випадковими цілими числами
		в діапазоні від 1 до 10
		та виведіть його значення.'''
print(comment)
m1 = np.random.randint(1, 11, size=(5, 5))
print('\nRESULT:')
print(m1)


3 Створіть масив розміром 5x5,
		заповніть його випадковими цілими числами
		в діапазоні від 1 до 10
		та виведіть його значення.

RESULT:
[[ 2  2  4 10  7]
 [ 1  8  6  1  1]
 [ 9  4  4  7  8]
 [ 8  4  3  9  7]
 [ 2  2  3  6 10]]


In [26]:
comment = '''\n4 Створіть масив розміром 4x4,
		заповніть його випадковими дійсними числами
		в діапазоні від 0 до 1
		та виведіть його значення.'''
print(comment)
m3 = np.random.rand(4, 4)
print('\nRESULT:')
print(m3)


4 Створіть масив розміром 4x4,
		заповніть його випадковими дійсними числами
		в діапазоні від 0 до 1
		та виведіть його значення.

RESULT:
[[0.92841016 0.93603925 0.91698458 0.78814112]
 [0.01238831 0.36991455 0.09819842 0.4122299 ]
 [0.83204584 0.13761997 0.63656904 0.45127458]
 [0.4069292  0.5703435  0.21666593 0.82721052]]


In [27]:
comment = '''\n5 Створіть два одновимірних масиви розміром 5,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та виконайте на них поелементні операції
		додавання, віднімання та множення.'''
print(comment)
m1 = np.random.randint(1, 11, size=5)
m2 = np.random.randint(1, 11, size=5)
print('sum:\n', m1 + m2)
print('subtraction:\n', m1 - m2)
print('multiplication:\n', m1 * m2)


5 Створіть два одновимірних масиви розміром 5,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та виконайте на них поелементні операції
		додавання, віднімання та множення.
sum:
 [13 13 11 12 13]
subtraction:
 [-3 -7 -3 -8 -7]
multiplication:
 [40 30 28 20 30]


In [28]:
comment = '''\n6 Створіть два вектори розміром 7,
		заповніть довільними числами
		та знайдіть їх скалярний добуток.'''
print(comment)
m1 = np.array([el for el in np.arange(7)])
m2 = np.array([el for el in np.arange(7)])
print('\nRESULT:')
print(np.dot(m1, m2))


6 Створіть два вектори розміром 7,
		заповніть довільними числами
		та знайдіть їх скалярний добуток.

RESULT:
91


In [29]:
comment = '''\n7 Створіть дві матриці розміром 2x2 та 2x3,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та перемножте їх між собою.'''
print(comment)
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 3))
c = np.dot(m1, m2)
print('\nRESULT:')
print(c)


7 Створіть дві матриці розміром 2x2 та 2x3,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та перемножте їх між собою.

RESULT:
[[ 82 104 100]
 [ 77 116 122]]


In [30]:
comment = '''\n8 Створіть матрицю розміром 3x3,
		заповніть її випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть її обернену матрицю.'''
print(comment)
m1 = np.random.randint(1, 11, size=(3, 3))
m2 = np.linalg.inv(m1)
print('\nRESULT:')
print(m2)


8 Створіть матрицю розміром 3x3,
		заповніть її випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть її обернену матрицю.

RESULT:
[[ 0.0617284   0.22222222 -0.20987654]
 [-0.19753086 -0.11111111  0.27160494]
 [ 0.22222222  0.         -0.05555556]]


In [31]:
comment = '''\n9 Створіть матрицю розміром 4x4,
		заповніть її випадковими дійсними числами
		в діапазоні від 0 до 1
		та транспонуйте її.'''
print(comment)
m1 = np.random.rand(4, 4)
m1T = m1.T
print('\nRESULT:')
print(m1T)


9 Створіть матрицю розміром 4x4,
		заповніть її випадковими дійсними числами
		в діапазоні від 0 до 1
		та транспонуйте її.

RESULT:
[[0.08306824 0.58807991 0.58878314 0.81480947]
 [0.2215306  0.57059361 0.25300532 0.86788787]
 [0.03038717 0.57035382 0.69292764 0.67122703]
 [0.51271282 0.6630704  0.57578288 0.92751175]]


In [32]:
comment = '''\n10 Створіть матрицю розміром 3x4 та вектор розміром 4,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та перемножте матрицю на вектор.'''
m1 = np.random.randint(1, 11, size=(3, 4))
v1 = np.random.randint(1, 11, size=(4))
print('\nRESULT:')
print(np.dot(m1, v1))


RESULT:
[118 200 150]


In [33]:
comment = '''\n11 Створіть матрицю розміром 2x3 та вектор розміром 3,
		заповніть їх випадковими дійсними числами
		в діапазоні від 0 до 1
		та перемножте матрицю на вектор.'''
print(comment)
m1 = np.random.rand(2, 3)
v1 = np.random.rand(3)
print('\nRESULT:')
print(np.dot(m1, v1))


11 Створіть матрицю розміром 2x3 та вектор розміром 3,
		заповніть їх випадковими дійсними числами
		в діапазоні від 0 до 1
		та перемножте матрицю на вектор.

RESULT:
[0.90910679 0.74179931]


In [34]:
comment = '''\n12 Створіть дві матриці розміром 2x2,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та виконайте їхнє поелементне множення.'''
print(comment)
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print('\nRESULT:')
print(np.multiply(m1, m2))


12 Створіть дві матриці розміром 2x2,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та виконайте їхнє поелементне множення.

RESULT:
[[30 16]
 [60 60]]


In [35]:
comment = '''\n13 Створіть дві матриці розміром 2x2,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть їх добуток.'''
print(comment)
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print('\nRESULT:')
print(np.dot(m1, m2))


13 Створіть дві матриці розміром 2x2,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть їх добуток.

RESULT:
[[20 55]
 [23 73]]


In [36]:
comment = '''\n14 Створіть матрицю розміром 5x5,
		заповніть її випадковими цілими числами
		в діапазоні від 1 до 100
		та знайдіть суму елементів матриці.'''
print(comment)
m1 = np.random.randint(1, 101, size=(5, 5))
print('\nRESULT:')
print(m1.sum())


14 Створіть матрицю розміром 5x5,
		заповніть її випадковими цілими числами
		в діапазоні від 1 до 100
		та знайдіть суму елементів матриці.

RESULT:
1242


In [37]:
comment = '''\n15 Створіть дві матриці розміром 4x4,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть їхню різницю.'''
print(comment)
m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))
print('\nRESULT:')
print(m1 - m2)


15 Створіть дві матриці розміром 4x4,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть їхню різницю.

RESULT:
[[ 4  2 -7 -2]
 [ 3  0  6  8]
 [ 0  3  1 -2]
 [-3  5 -2  0]]


In [38]:
comment = '''\n16 Створіть матрицю розміром 3x3,
		заповніть її випадковими дійсними числами
		в діапазоні від 0 до 1
		та знайдіть вектор-стовпчик, що містить
		суму елементів кожного рядка матриці.'''
print(comment)
m1 = np.random.rand(3, 3)
print('\nRESULT:')
print(np.array([[el.sum()] for el in m1[:]]))


16 Створіть матрицю розміром 3x3,
		заповніть її випадковими дійсними числами
		в діапазоні від 0 до 1
		та знайдіть вектор-стовпчик, що містить
		суму елементів кожного рядка матриці.

RESULT:
[[1.63015566]
 [1.53439271]
 [1.67917958]]


In [39]:
comment = '''\n17 Створіть матрицю розміром 3x4
		з довільними цілими числами
		і створінь матрицю з квадратами цих чисел.'''
print(comment)
m1 = np.random.randint(1, 11, size=(3, 4))
print(m1)
print('\nRESULT:')
print(np.square(m1))


17 Створіть матрицю розміром 3x4
		з довільними цілими числами
		і створінь матрицю з квадратами цих чисел.
[[ 9  8 10  4]
 [ 1  3  7  1]
 [ 6  9  1  9]]

RESULT:
[[ 81  64 100  16]
 [  1   9  49   1]
 [ 36  81   1  81]]


In [40]:
comment = '''\n18 Створіть вектор розміром 4,
		заповніть його випадковими цілими числами
		в діапазоні від 1 до 50
		та знайдіть вектор з квадратними коренями цих чисел.'''
print(comment)
m1 = np.random.randint(1, 51, size=(4))
print(m1)
print('\nRESULT:')
print(np.sqrt(m1))


18 Створіть вектор розміром 4,
		заповніть його випадковими цілими числами
		в діапазоні від 1 до 50
		та знайдіть вектор з квадратними коренями цих чисел.
[30  3 38 38]

RESULT:
[5.47722558 1.73205081 6.164414   6.164414  ]
