In [ ]:
# Домашнє завдання 1
import numpy as np
comment = '''\n1 Створіть одновимірний масив (вектор)
		з першими 10-ма натуральними числами
		та виведіть його значення.'''
print(comment)
m1 = np.arange(1, 11)
print('\nRESULT:')
print(m1)
m1_1 = np.linspace(1, 10, num=10)
print('\nRESULT:')
print(m1_1)


1 Створіть одновимірний масив (вектор)
		з першими 10-ма натуральними числами
		та виведіть його значення.

RESULT:
[ 1  2  3  4  5  6  7  8  9 10]

RESULT:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

2 Створіть двовимірний масив (матрицю) розміром 3x3,
		заповніть його нулями
		та виведіть його значення.

RESULT:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

3 Створіть масив розміром 5x5,
		заповніть його випадковими цілими числами
		в діапазоні від 1 до 10
		та виведіть його значення.

RESULT:
[[ 4  2  6  7  9]
 [ 7  2  2  4  9]
 [ 7  7  5  5  2]
 [10  2  3  2  9]
 [ 8  8  2  7  4]]

4 Створіть масив розміром 4x4,
		заповніть його випадковими дійсними числами
		в діапазоні від 0 до 1
		та виведіть його значення.

RESULT:
[[0.19171214 0.4731612  0.73742614 0.37020504]
 [0.54755872 0.25790038 0.00684149 0.30030716]
 [0.38281623 0.85726241 0.34300676 0.64170458]
 [0.42518817 0.71664686 0.71006249 0.74703817]]

5 Створіть два одновимірних масиви розміром 5,
		заповніть їх випадковими цілими числами
		в д

In [ ]:
comment = '''\n2 Створіть двовимірний масив (матрицю) розміром 3x3,
		заповніть його нулями
		та виведіть його значення.'''
print(comment)
m1 = np.zeros((3,3), dtype=int)
print('\nRESULT:')
print(m1)

In [ ]:
comment = '''\n3 Створіть масив розміром 5x5,
		заповніть його випадковими цілими числами
		в діапазоні від 1 до 10
		та виведіть його значення.'''
print(comment)
m1 = np.random.randint(1, 11, size=(5, 5))
print('\nRESULT:')
print(m1)

In [ ]:
comment = '''\n4 Створіть масив розміром 4x4,
		заповніть його випадковими дійсними числами
		в діапазоні від 0 до 1
		та виведіть його значення.'''
print(comment)
m3 = np.random.rand(4, 4)
print('\nRESULT:')
print(m3)

In [ ]:
comment = '''\n5 Створіть два одновимірних масиви розміром 5,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та виконайте на них поелементні операції
		додавання, віднімання та множення.'''
print(comment)
m1 = np.random.randint(1, 11, size=5)
m2 = np.random.randint(1, 11, size=5)
print('sum:\n', m1 + m2)
print('subtraction:\n', m1 - m2)
print('multiplication:\n', m1 * m2)

In [ ]:
comment = '''\n6 Створіть два вектори розміром 7,
		заповніть довільними числами
		та знайдіть їх скалярний добуток.'''
print(comment)
m1 = np.array([el for el in np.arange(7)])
m2 = np.array([el for el in np.arange(7)])
print('\nRESULT:')
print(np.dot(m1, m2))

In [ ]:
comment = '''\n7 Створіть дві матриці розміром 2x2 та 2x3,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та перемножте їх між собою.'''
print(comment)
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 3))
c = np.dot(m1, m2)
print('\nRESULT:')
print(c)

In [ ]:
comment = '''\n8 Створіть матрицю розміром 3x3,
		заповніть її випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть її обернену матрицю.'''
print(comment)
m1 = np.random.randint(1, 11, size=(3, 3))
m2 = np.linalg.inv(m1)
print('\nRESULT:')
print(m2)

In [ ]:
comment = '''\n9 Створіть матрицю розміром 4x4,
		заповніть її випадковими дійсними числами
		в діапазоні від 0 до 1
		та транспонуйте її.'''
print(comment)
m1 = np.random.rand(4, 4)
m1T = m1.T
print('\nRESULT:')
print(m1T)

In [ ]:
comment = '''\n10 Створіть матрицю розміром 3x4 та вектор розміром 4,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та перемножте матрицю на вектор.'''
m1 = np.random.randint(1, 11, size=(3, 4))
v1 = np.random.randint(1, 11, size=(4))
print('\nRESULT:')
print(np.dot(m1, v1))

In [ ]:
comment = '''\n11 Створіть матрицю розміром 2x3 та вектор розміром 3,
		заповніть їх випадковими дійсними числами
		в діапазоні від 0 до 1
		та перемножте матрицю на вектор.'''
print(comment)
m1 = np.random.rand(2, 3)
v1 = np.random.rand(3)
print('\nRESULT:')
print(np.dot(m1, v1))

In [ ]:
comment = '''\n12 Створіть дві матриці розміром 2x2,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та виконайте їхнє поелементне множення.'''
print(comment)
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print('\nRESULT:')
print(np.multiply(m1, m2))

In [ ]:
comment = '''\n13 Створіть дві матриці розміром 2x2,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть їх добуток.'''
print(comment)
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print('\nRESULT:')
print(np.dot(m1, m2))

In [ ]:
comment = '''\n14 Створіть матрицю розміром 5x5,
		заповніть її випадковими цілими числами
		в діапазоні від 1 до 100
		та знайдіть суму елементів матриці.'''
print(comment)
m1 = np.random.randint(1, 101, size=(5, 5))
print('\nRESULT:')
print(m1.sum())

In [ ]:
comment = '''\n15 Створіть дві матриці розміром 4x4,
		заповніть їх випадковими цілими числами
		в діапазоні від 1 до 10
		та знайдіть їхню різницю.'''
print(comment)
m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))
print('\nRESULT:')
print(m1 - m2)

In [ ]:
comment = '''\n16 Створіть матрицю розміром 3x3,
		заповніть її випадковими дійсними числами
		в діапазоні від 0 до 1
		та знайдіть вектор-стовпчик, що містить
		суму елементів кожного рядка матриці.'''
print(comment)
m1 = np.random.rand(3, 3)
print('\nRESULT:')
print(np.array([[el.sum()] for el in m1[:]]))

In [ ]:
comment = '''\n17 Створіть матрицю розміром 3x4
		з довільними цілими числами
		і створінь матрицю з квадратами цих чисел.'''
print(comment)
m1 = np.random.randint(1, 11, size=(3, 4))
print(m1)
print('\nRESULT:')
print(np.square(m1))

In [ ]:
comment = '''\n18 Створіть вектор розміром 4,
		заповніть його випадковими цілими числами
		в діапазоні від 1 до 50
		та знайдіть вектор з квадратними коренями цих чисел.'''
print(comment)
m1 = np.random.randint(1, 51, size=(4))
print(m1)
print('\nRESULT:')
print(np.sqrt(m1))